-- Schema for Seed Monitoring System

-- 1. Create the seed_counts table
CREATE TABLE seed_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_id INTEGER NOT NULL,
    current_count INTEGER NOT NULL DEFAULT 0,
    flow_rate INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'healthy', -- 'healthy', 'warning', 'error'
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Turn on Row Level Security (RLS) to secure the data
ALTER TABLE seed_counts ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy that allows anyone with the anon key to READ the data
CREATE POLICY "Allow public read access"
ON seed_counts
FOR SELECT
TO anon, authenticated
USING (true);

-- 4. Create a policy that allows the ESP32 (acting anonymously) to UPDATE the data
-- (Note: In a true production environment, you would use an authenticated service_role key for the ESP32, 
-- but for $0 budget hobby projects, anonymous posting with hidden URLs is acceptable.)
CREATE POLICY "Allow public insert and update"
ON seed_counts
FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 5. Enable Realtime broadcasting so the PWA updates instantly!
ALTER PUBLICATION supabase_realtime ADD TABLE seed_counts;

-- Let's populate the initial 6 default outlets so the dashboard has rows to listen to right away
INSERT INTO seed_counts (outlet_id, current_count, flow_rate, status) VALUES
(1, 0, 0, 'healthy'),
(2, 0, 0, 'healthy'),
(3, 0, 0, 'healthy'),
(4, 0, 0, 'healthy'),
(5, 0, 0, 'healthy'),
(6, 0, 0, 'healthy');
